name: Publicacion Automatica

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Compilando para Android y Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Android
        run: flutter build apk --release

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Crear Release y Subir Archivos
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Publicación Automática - ${{ github.ref_name }}"
          generate_release_notes: true
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/x64/runner/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
